version: "3.9"
services:
  pg:
    image: postgres:16
    container_name: levelog-pg
    environment:
      POSTGRES_DB: arena
      POSTGRES_USER: arena
      POSTGRES_PASSWORD: arena123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U arena -d arena" ]
      interval: 5s
      timeout: 3s
      retries: 10
